import '@/styles/globals.css';

import { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReactQueryProvider } from '@/components/providers/ReactQuery';
import SessionWrapper from '@/components/SessionWrapper';
import { MainLayout } from '@/components/templates/MainLayout';

import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-primary' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={cn(inter.variable, 'font-primary')} suppressHydrationWarning>
          <div id="modal" />
          <ReactQueryProvider>
            <MainLayout>
              <main>{children}</main>
            </MainLayout>
          </ReactQueryProvider>
        </body>
      </html>
    </SessionWrapper>
  );
};

export default RootLayout;
