import '@/styles/globals.css';

import { Metadata } from 'next';
import { Inter } from 'next/font/google';

import SessionWrapper from '@/components/SessionWrapper';

const inter = Inter({ subsets: ['latin'], variable: '--font-primary' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionWrapper>
  );
};
export default RootLayout;
